services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    environment:
      - DATABASE_URL=${DATABASE_URL}

  test-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=pokemon_quiz_test
    ports:
      - "3306:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql

volumes:
  mysql_test_data: 